version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    
    ports:
      - "8501:8501"

    environment:
      - BACKEND_URL=http://backend:8000

    networks:
      - app-network

    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
